"use strict";
let batman = "Batman";
let linternaVerde = "Linterna Verde";
let volcanNegro = "Volcan Negro";
console.log(batman);
console.log(linternaVerde);
console.log(volcanNegro);
let concatenar = "Los heroes son: " + batman + ", " + linternaVerde + ", " + volcanNegro;
let concat = `Los heroes: son: ${batman} ${linternaVerde} ${volcanNegro}`;
console.log(concat);
