"use strict";
let vengador = "Superman";
let existe;
let derrotas;
vengador = "Dr. Strange";
console.log(vengador.charAt(0));
vengador = 150.5555;
console.log(vengador.toFixed(2));
vengador = true;
console.log(vengador);
